[package]
name = "test-crs"
version = "0.1.0"
edition = "2021"
authors = [ "Colin Daniels <colin.r.daniels@gmail.com>" ]

[dependencies]
pest = "2.2"
pest_derive = "2.2"
regex = "1.6"
thiserror = "1.0"
hyperscan = { version = "0.3" }
lazy_static = "1.4"

